### PR TITLE
Mingw/5.2.3

### PR DESCRIPTION
**Pull request by SSE4**
initial support of MinGW build
https://github.com/bincrafters/community/issues/42

### CODE REVIEW

**Comment by SSE4** [comment]
Gerald has an idea how to specify build requirements in build.py instead of conanfile.py
https://github.com/bincrafters/conan-bazel_installer/blob/testing/0.8.0/build.py#L29
however, I don't know how to make it for MinGW only
if someone has such experience with conan package tools / bincrafters package tools, please make changes needed

**Review by ghost — APPROVED** [review]
Looking good!

**Comment by solvingj** [comment]
I pushed some changes to this branch.  Disabled travis, reduced appveyor to mingw only.  It looks like build number 8 out of 24 is faliing on appveyor:  

https://ci.appveyor.com/project/BinCrafters/conan-lzma/build/1.0.18#L6556


```
[settings]
arch=x86
build_type=Release
compiler=gcc
compiler.exception=sjlj
compiler.libcxx=libstdc++
compiler.threads=posix
compiler.version=4.9
[options]
lzma:shared=True
[env]
```

 ```C:/Users/appveyor/.conan/data/mingw_installer/1.0/conan/stable/package/9d2106de64b6c7d524df4a0cf2158178daef4e9c/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file `.libs/liblzma_w32res.o' is incompatible with i386 output```

**Comment by sigmoidal** [comment]
The recipe looks good, I compiled with mingw locally, np. Needs the `is_mingw` though to be included.

**Review by sigmoidal — CHANGES_REQUESTED** [review]
Please insert back the `is_mingw` property. Other than that it looks good.

**Comment by sigmoidal** [comment]
Not sure if it helps you, but I traced the problem to the detection of ld. look at this line in a failing log:

https://ci.appveyor.com/project/BinCrafters/conan-lzma/build/1.0.23#L6121

It detects x86_64 mingw ld instead of the i686 (x86) ld that it should. This is not happening locally, I tried the exact same configuration and it builds like a charm.

i will resume tomorrow if necessary.

**Comment by SSE4** [comment]
now run into the conan issue https://github.com/conan-io/conan/issues/2346

**Comment by SSE4** [comment]
outdated and no longer needed (commits are in testing/stable already btw)

**Pull request closed without merging**
